spring:
  application:
    name: security
  datasource:
    url: jdbc:h2:tcp://localhost/~/workspace/h2/security
    username: sa
    password:
    driver-class-name: org.h2.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
  session:
    redis:
      namespace: spring:session
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
